# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [6]:
ser1 = np.random.randint(1 , high = 4 , size = 100 , dtype = "int")
ser2 = np.random.randint(1 , high = 3 , size = 100 , dtype = "int")
ser3 = np.random.randint(10000 , high = 30000 , size = 100 , dtype = "l")

In [7]:
ser1

array([3, 3, 1, 2, 3, 2, 1, 1, 1, 3, 1, 2, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3,
       2, 3, 1, 2, 3, 1, 3, 1, 3, 1, 1, 1, 2, 1, 3, 1, 1, 1, 3, 1, 1, 1,
       2, 3, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 1, 2, 3, 1, 3, 1, 3, 2, 2,
       1, 2, 2, 3, 2, 3, 2, 2, 1, 3, 1, 3, 3, 2, 3, 2, 1, 3, 1, 2, 3, 2,
       1, 2, 3, 3, 2, 2, 3, 2, 1, 3, 2, 3])

In [8]:
ser2

array([1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1,
       2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1])

In [9]:
ser3

array([20188, 25525, 13163, 29253, 14344, 16590, 23945, 14470, 27499,
       22036, 11931, 12819, 18400, 15576, 15122, 13082, 10485, 15096,
       27577, 19115, 15970, 22545, 13981, 21130, 11019, 12707, 12586,
       18494, 27852, 10742, 14888, 29689, 20268, 28933, 10963, 25277,
       19698, 16399, 25821, 13993, 12989, 21566, 29535, 19214, 22248,
       18279, 16396, 16716, 12189, 12206, 21329, 22215, 26033, 20631,
       25964, 10748, 20753, 15152, 18854, 27952, 15618, 24289, 13310,
       24416, 29629, 23758, 14664, 24897, 27053, 11360, 27436, 13755,
       15969, 26831, 13555, 13920, 27143, 20919, 13740, 25934, 19059,
       25456, 11422, 26122, 18084, 12631, 28785, 20866, 11294, 23244,
       10133, 24708, 26097, 20611, 14285, 17965, 23084, 24378, 25117,
       19093])

### Step 3. Let's create a DataFrame by joinning the Series by column

In [11]:
ser1 = pd .Series(ser1)
ser2 = pd .Series(ser2)
ser3 = pd .Series(ser3)

In [14]:
series = pd.concat([ser1 ,ser2 , ser3] ,axis = 1 ,ignore_index= True)

In [15]:
series

0  1      2
0   3  1  20188
1   3  2  25525
2   1  1  13163
3   2  1  29253
4   3  1  14344
.. .. ..    ...
95  2  1  17965
96  1  1  23084
97  3  2  24378
98  2  2  25117
99  3  1  19093

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [17]:
series.rename(columns= { 0 : "bedrs" , 1 : "bathrs" , 2 : "price_sqr_meter"} , inplace = True)

In [18]:
series

bedrs  bathrs  price_sqr_meter
0       3       1            20188
1       3       2            25525
2       1       1            13163
3       2       1            29253
4       3       1            14344
..    ...     ...              ...
95      2       1            17965
96      1       1            23084
97      3       2            24378
98      2       2            25117
99      3       1            19093

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [21]:
bigcolumn = pd .concat ([ser1,ser2,ser3] , axis  =  0)
bigcolumn


0         3
1         3
2         1
3         2
4         3
      ...  
95    17965
96    23084
97    24378
98    25117
99    19093
Length: 300, dtype: int32

In [23]:
bigcolumn = pd.DataFrame(bigcolumn)
bigcolumn

0
0       3
1       3
2       1
3       2
4       3
..    ...
95  17965
96  23084
97  24378
98  25117
99  19093

[300 rows x 1 columns]

In [26]:
bigcolumn.rename({0 : "bigcolumn"} , inplace = True)

In [27]:
bigcolumn

0
bigcolumn      3
1              3
2              1
3              2
4              3
...          ...
95         17965
96         23084
97         24378
98         25117
99         19093

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

yes

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [31]:
bigcolumn.reset_index(drop=True , inplace =True)

In [32]:
bigcolumn

0
0        3
1        3
2        1
3        2
4        3
..     ...
295  17965
296  23084
297  24378
298  25117
299  19093

[300 rows x 1 columns]